[package]
name = "striped_hashtable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
rand_chacha = "0.3.1"
bustle = "0.4.2"
serde = { version = "1.0.131", features = ["derive"] }
csv = "1.1.6"
structopt = "0.3.25"

